### ISSUE TITLE
Trakt API is down 

### ISSUE THREAD

**Issue by icpryde** [trakt/api-help#27]
Trakt API seems to have been down almost all day? Can’t use any of my apps or anything it just gives me errors and doesn’t load any of my lists.

**Comment by tysonkerridge** [comment]
Also had some weird behaviour though the status page doesn’t show any outages etc. I don’t have any specific error details to share (haven’t debugged it) but from general use there’s a bunch of things failing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kevincador** [comment]
Also had a lot of issues. Still had some reports during the night. 
I saw myself a lot of 500 issues. Especially with endpoints that are not caches as much as others. Like check-in/watching endpoints. 
I’m in the EU region. Don’t know if it’s relevant. Reports coming from different regions...
I don’t know what the status page is checking but could be great to maybe check something that is not cached to much to avoid false-negatives.

**Comment by tysonkerridge** [comment]
Can confirm similar endpoints were the ones with issues, users checkin/watching, shows watched progress, etc.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonathanantoine** [comment]
Same issue here, example of requested uri : 

`https://api.trakt.tv/shows/110288?extended=full%2Cimages&usedForUniqueQueryKeyByLanguage=English`

Headers :
`{Accept: application/json trakt-api-version: 2 trakt-api-key: nothere }`

Answer content : 
`{"message":"Internal server error. Please open a support issue and include your full API request and response, including all headers."}`

**Comment by rectifyer** [comment]
This should be fixed now, looks like a few API servers got messed up. I tested the above API method and it loads ok for me now.

**Comment by b1n4ryk1lla** [comment]
still down getting 500 errors

**Comment by rectifyer** [comment]
We can't do anything without specific API requests including all headers and data for both the request and response.

**Comment by eliehaykal** [comment]
It seems to be happening mostly around 1 AM to 4 AM GMT time. Could it be a load issue?

**Comment by icpryde** [comment]
Still getting errors trying to load my lists...is this due to server loads or is something else wrong?

**Comment by eliehaykal** [comment]
I managed to log this request which threw an HTTP 500 error:

**Headers:**

cache-control →max-age=0, private, no-cache, no-store, must-revalidate
cf-railgun →25d893222c 6.92 0.027248 0030 57da
cf-ray →4ac230974dfdc03b-MRS
content-type →application/json; charset=utf-8
date →Wed, 20 Feb 2019 16:01:05 GMT
expect-ct →max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server →cloudflare
status →500
vary →Accept-Encoding
x-content-type-options →nosniff
x-frame-options →SAMEORIGIN
x-request-id →940ae00c-af86-4ed1-8193-6e840497639e
x-runtime →0.004461
x-xss-protection →1; mode=block

**Body:**

{
    "message": "Internal server error. Please open a support issue and include your full API request and response, including all headers."
}

**API Call:**
https://api.trakt.tv/movies/trending

**Comment by geogolem** [comment]
i also seem to be experiencing similar errors today.

**Comment by rectifyer** [comment]
@eliehaykal thanks for the example code, that is really the only way we can try and reproduce the issues.

I just pushed a fix and hopefully things return to normal now.

**Comment by geogolem** [comment]
the problem seems to be resolved. thanks

**Comment by eliehaykal** [comment]
> @eliehaykal thanks for the example code, that is really the only way we can try and reproduce the issues.
> 
> I just pushed a fix and hopefully things return to normal now.

Thank you for your prompt support as always. Does the fix need some time to replicate to other nodes?
I have already noticed a large reduction in the number of HTTP 500 errors.

**Comment by icpryde** [comment]
For the future how do I get a report log that I can share to help you guys in the future?

**Comment by rectifyer** [comment]
> Thank you for your prompt support as always. Does the fix need some time to replicate to other nodes?
> I have already noticed a large reduction in the number of HTTP 500 errors.

All API servers have the fix, so its possible the 500 errors are related to something else or weren't fixed by my update.

> For the future how do I get a report log that I can share to help you guys in the future?

That depends on how you're using the API. If you're using a library, there should be a way to dump out the raw API response and headers.

**Comment by eliehaykal** [comment]
@rectifyer Hello,
Some users are reporting rare HTTP 502 issues. Can you please check if there are any pending issues.

<-- POST https://api.trakt.tv/oauth/token
Headers start 
Content-type: application/json
trakt-api-version: 2
trakt-api-key: aaaaa
Headers end 

Body: {"client_id":"aaaaa","client_secret":"aaaa","code":"aaaaa","grant_type":"authorization_code","redirect_uri":"aaa"}

Response: 
code: 502
message: 
Headers start 
date: Sun, 24 Feb 2019 23:00:43 GMT
content-type: text/html; charset=UTF-8
set-cookie: __cfduid=d1a3f76c73972a59bb2f1931b784f1c8a1551049243; expires=Mon, 24-Feb-20 23:00:43 GMT; path=/; domain=.trakt.tv; HttpOnly
cf-railgun: 1fee97e13d 99.99 0.173553 0030 57da
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
set-cookie: cf_use_ob=0; path=/; expires=Sun, 24-Feb-19 23:01:13 GMT
expires: Thu, 01 Jan 1970 00:00:01 GMT
pragma: no-cache
server: cloudflare
cf-ray: 4ae58ccb3ab76005-MRS
Cache-Control: public, max-age=10
Headers end 

Body: null

**Comment by eliehaykal** [comment]
More 502 errors in the attached text file which happened Friday at around 22:00 GMT time
This is happening when users attempt to login.
[502.txt](https://github.com/trakt/api-help/files/2921819/502.txt)

**Comment by eliehaykal** [comment]
503 errors happening now:

cf-railgun →3003b948d0 stream 0.000000 0210 57da
cf-ray →4b1d578ec9efa472-BEY
content-length →0
date →Sun, 03 Mar 2019 17:31:05 GMT
expect-ct →max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server →cloudflare
status →503

**Comment by icpryde** [comment]
Trakt API has been so unstable the last few weeks :( it was pretty good though the last week but it’s back to its old ways :(

**Comment by rectifyer** [comment]
I just added 5 more API servers in which should help lower response times. We are still investigating the recent performance issues and it has been tough to pin point an exact cause so far.

**Comment by eliehaykal** [comment]
> I just added 5 more API servers in which should help lower response times. We are still investigating the recent performance issues and it has been tough to pin point an exact cause so far.

Thank you, the API is much stable now.

**Comment by eliehaykal** [comment]
The past 2 days have been unstable. Are there any new findings on the issue?

**Comment by rectifyer** [comment]
Sundays and Mondays typically have the highest API load, so probably still related to that. The additional servers seems to have definitely helped, but not fully solved the issue. I'm still investigating the most used API methods and trying to optimize and speed those up.

**Comment by eliehaykal** [comment]
> Sundays and Mondays typically have the highest API load, so probably still related to that. The additional servers seems to have definitely helped, but not fully solved the issue. I'm still investigating the most used API methods and trying to optimize and speed those up.

There was a slight outage 1 hour ago from my post. I've been taking note of these outages and they seem to happen mostly in the 00:00 to 6:00 GMT Range

**Comment by icpryde** [comment]
The api seems to be down right now? Things are not loading or working for me

**Comment by icpryde** [comment]
been a full day and it still seems to be down?

**Comment by rectifyer** [comment]
>been a full day and it still seems to be down?

@icpryde looks ok from our side. Please provide a full api call including all headers and responses.

**Comment by icpryde** [comment]
@rectifyer ....how would I do that exactly? sorry I'm new to all this.

**Comment by icpryde** [comment]
all seems good now i just  re authenticated my stuff and its working again

**Comment by kevincador** [comment]
Received a report from a user tonight. Almost all requests failed for him.

Here is one of the error:

```
‼️‼️‼️ 2019-03-24 20:27:27.611 [Error] [📺Trakt] > API error: Error Domain=tv.trakt.InternalAPIErrorDomain Code=0 "(null)" UserInfo={tv.trakt.InternalAPIErrorRequest=<NSMutableURLRequest: 0x280ee5390> { URL: https://api.trakt.tv/sync/history/shows?limit=400 }, tv.trakt.InternalAPIErrorResponse=<NSHTTPURLResponse: 0x2848b5760> { URL: https://api.trakt.tv/sync/history/shows?limit=400 } { Status Code: 503, Headers {
    "Content-Length" =     (
        0
    );
    Date =     (
        "Sun, 24 Mar 2019 19:27:27 GMT"
    );
    Server =     (
        cloudflare
    );
    "cf-railgun" =     (
        "80fbc9aaa0 0030 normal 57da"
    );
    "cf-ray" =     (
        "4bcb0ae3df767d02-MUC"
    );
    "expect-ct" =     (
        "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
    );
} }} ‼️‼️‼️
```

**Comment by jonathanantoine** [comment]
Hello,

I've got reports from brazilan users too if it can help :

> I realized that it's something related to the hour I try to use the app (something around midnight in Brazil -3h ).
